// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZES4ZA0U_LuEUwSd5gJQ7V6g28KyAmAE',
    appId: '1:980534098321:web:a2b444599f81e67efd4230',
    messagingSenderId: '980534098321',
    projectId: 'booklyapp-b39b0',
    authDomain: 'booklyapp-b39b0.firebaseapp.com',
    storageBucket: 'booklyapp-b39b0.firebasestorage.app',
    measurementId: 'G-VN1J5F2KPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC465ZRgD5mg01q6jVx2meo_5ENXWCm1sc',
    appId: '1:980534098321:android:48bb0aa22a185cc4fd4230',
    messagingSenderId: '980534098321',
    projectId: 'booklyapp-b39b0',
    storageBucket: 'booklyapp-b39b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZd7ZskyOF9EP5CJ-l4T7MqG8m8fwGfqI',
    appId: '1:980534098321:ios:8f1756263597696bfd4230',
    messagingSenderId: '980534098321',
    projectId: 'booklyapp-b39b0',
    storageBucket: 'booklyapp-b39b0.firebasestorage.app',
    iosBundleId: 'com.example.bookly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZd7ZskyOF9EP5CJ-l4T7MqG8m8fwGfqI',
    appId: '1:980534098321:ios:8f1756263597696bfd4230',
    messagingSenderId: '980534098321',
    projectId: 'booklyapp-b39b0',
    storageBucket: 'booklyapp-b39b0.firebasestorage.app',
    iosBundleId: 'com.example.bookly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZES4ZA0U_LuEUwSd5gJQ7V6g28KyAmAE',
    appId: '1:980534098321:web:ad9c579314abbf05fd4230',
    messagingSenderId: '980534098321',
    projectId: 'booklyapp-b39b0',
    authDomain: 'booklyapp-b39b0.firebaseapp.com',
    storageBucket: 'booklyapp-b39b0.firebasestorage.app',
    measurementId: 'G-KQVG97F82K',
  );
}
